-- Migration number: 0006 	 2025-01-21T10:00:00.000Z
-- Adicionar campos faltantes do schema MySQL à tabela lojas (Parte 1)

-- Adicionar campos básicos de identificação e contato
ALTER TABLE lojas ADD COLUMN status INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN login TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN versao TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN instalado TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN data DATE DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN senha TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN cnpj TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN ie TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN nome TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN fantasia TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN fone TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN cep TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN logradouro TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN numero TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN complemento TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN bairro TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN idcidade INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN cidade TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN iduf INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN uf TEXT DEFAULT NULL;