-- Migration number: 0007 	 2025-01-21T10:01:00.000Z
-- Adicionar campos faltantes do schema MySQL à tabela lojas (Parte 2)

-- Adicionar campos de configuração e sistema
ALTER TABLE lojas ADD COLUMN regime TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN modelo INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN serie INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN nf INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN pedido INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN ordem INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN romaneio INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN bancoservidor TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN ipservidor TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN emailhost TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN emailport TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN emailusername TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN emailpassword TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN emailssl INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN emailtls INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN emailreqconfirmation INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN certificado TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN icmscredito DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN federal DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN estadual DECIMAL(10,2) DEFAULT NULL;