-- Migration number: 0008 	 2025-01-21T10:02:00.000Z
-- Adicionar campos faltantes do schema MySQL à tabela lojas (Parte 3)

-- Adicionar campos fiscais e tributários
ALTER TABLE lojas ADD COLUMN ambiente TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN ippt TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN csticms TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN cstpis TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN cstcofins TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN cstipi TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN aliquotaicmsreducao DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN aliquotapis DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN aliquotacofins DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN aliquotaipi DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN csticmsreducao TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN cstdevolucao INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN orientacao INTEGER DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN atualizacao DATE DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN serasa DECIMAL(10,2) DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN nomedocontato TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN codigodaloja TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN modsetiqtscomposicao TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN instaladopro TEXT DEFAULT NULL;
ALTER TABLE lojas ADD COLUMN obs TEXT DEFAULT NULL;