import { D1UpdateEndpoint } from "chanfana";
import { HandleArgs } from "../../types";
import { LojaModel } from "./base";

export class LojaUpdate extends D1UpdateEndpoint<HandleArgs> {
  _meta = {
    model: LojaModel,
    fields: LojaModel.schema.pick({
      // Excluir banco e idloja dos campos atualizáveis pois são parte da chave primária
      // Incluindo todos os campos disponíveis no schema
      status: true,
      login: true,
      versao: true,
      instalado: true,
      backup: true,
      data: true,
      senha: true,
      cnpj: true,
      ie: true,
      nome: true,
      fantasia: true,
      fone: true,
      cep: true,
      logradouro: true,
      numero: true,
      complemento: true,
      bairro: true,
      idcidade: true,
      cidade: true,
      iduf: true,
      uf: true,
      regime: true,
      modelo: true,
      serie: true,
      nf: true,
      pedido: true,
      ordem: true,
      romaneio: true,
      bancoservidor: true,
      ipservidor: true,
      emailhost: true,
      emailport: true,
      emailusername: true,
      emailpassword: true,
      emailssl: true,
      emailtls: true,
      emailreqconfirmation: true,
      certificado: true,
      icmscredito: true,
      federal: true,
      estadual: true,
      ambiente: true,
      ippt: true,
      csticms: true,
      cstpis: true,
      cstcofins: true,
      cstipi: true,
      aliquotaicmsreducao: true,
      aliquotapis: true,
      aliquotacofins: true,
      aliquotaipi: true,
      csticmsreducao: true,
      cstdevolucao: true,
      orientacao: true,
      atualizacao: true,
      serasa: true,
      nomedocontato: true,
      codigodaloja: true,
      modsetiqtscomposicao: true,
      instaladopro: true,
      obs: true,
      anydesk: true,
      versaocontrol: true,
      sat: true,
      contato: true,
      email: true,
      mensalidade: true,
      michel: true,
      michelloja: true,
      micheltabela: true,
      ddd: true,
      foneresp: true,
      monitor: true,
      uuid: true,
      hoptodesk: true,
      loja: true,
      marca: true,
      vencimento: true,
      ultimoerrorelicar: true,
      ultimoerrointegracao: true,
      qdtregistrosreplicar: true,
      replicar: true,
      reglocal: true,
      regservidor: true,
      versaosinc: true,
      tempogastoreplicar: true,
      regintegracao: true,
      versaol: true,
      versaopro: true,
      versaoomnni: true,
      versaolite: true,
      versaoparelelo: true,
      versaodunamis: true,
      versaointegracao: true,
      versaoatualizador: true,
      versaotemp: true,
      ipvpn: true,
      integracao: true,
    }),
  };
}